#!/bin/bash -e

# Usage: /sbin/roundcube-backup
backupPath="/data/backup"
backupFileSuffix="-roundcube.tar.gz"
backupDbSuffix="-roundcube-db.tar.gz"
databaseFile="database.sql"

source /container/run/environment.sh

# delete backups that are over $ROUNDCUBE_BACKUP_TTL days
find $backupPath -type f -mtime +$ROUNDCUBE_BACKUP_TTL -exec rm {} \;

# date format for the dump file name
dateFileFormat="+%Y%m%dT%H%M%S"
backupFilePath="$backupPath/$(date "$dateFileFormat")$backupFileSuffix"

# save config and plugins except default ones
tar -czf $backupFilePath -C / var/www/roundcube
chmod 600 $backupFilePath

# backup database
. /container/service/backup/assets/tool/roundcube-get-db-params
rm -rf $databaseFile || true

# use ssl
if [ -n "$cert" ] && [ -n "$key" ]; then
  mysqldump -u $databaseUser -p$databasePassword --host $host --ssl --ssl-cert $cert --ssl-key $key $database > $databaseFile
else
  mysqldump -u $databaseUser -p$databasePassword --host $host $database > $databaseFile
fi

backupFilePath="$backupPath/$(date "$dateFileFormat")$backupDbSuffix"
tar -czf $backupFilePath $databaseFile
chmod 600 $backupFilePath

rm -rf $databaseFile

exit 0
